### ISSUE TITLE
Parts list?

### ISSUE THREAD

**Issue by Skeyelab** [shaduzlabs/pink-0#1]
So I just ordered 6 PCBs from batchpcb.com. I have experience w through hole components, but not surface mount and I'm not exactly sure how to order the resistors and capacitors. Everything else, I'm pretty comfy with. 

Can you provide some info on this?

Thanks
Eric (from the Discourse thread)

**Comment by shaduzlabs** [comment]
see hardware/BOM.txt
more documentation will follow
