### ISSUE TITLE
pink fails to build

### ISSUE THREAD

**Issue by endlesssummer2000** [shaduzlabs/pink-0#11]
hi,

when running the install script, things seem to trip up at Audio.cpp (?)

> [ 14%] Building CXX object CMakeFiles/pink.dir/src/Audio.cpp.o
> In file included from /home/pi/pink-0/src/Audio.h:10:0,
>                  from /home/pi/pink-0/src/Audio.cpp:8:
> /home/pi/pink-0/src/Engine.h:65:49: error: **'ableton::Link::Timeline' has not been declared**
>    void renderMetronomeIntoBuffer(ableton::Link::Timeline timeline,
>                                                  ^~~~~~~~
> In file included from /home/pi/pink-0/src/Audio.cpp:8:0:
> /home/pi/pink-0/src/Audio.h:62:33: **error: 'stl' is not a member of 'ableton::platforms'**
>    ableton::link::HostTimeFilter<ableton::platforms::stl::Clock> m_hostTimeFilter;
>                                  ^~~~~~~
> /home/pi/pink-0/src/Audio.h:62:33: error: **'stl' is not a member of 'ableton::platforms'**
> /home/pi/pink-0/src/Audio.h:62:63: error: template argument 1 is invalid
>    ableton::link::HostTimeFilter<ableton::platforms::stl::Clock> m_hostTimeFilter;
>                                                                ^
> /home/pi/pink-0/src/Audio.cpp: In static member function 'static int sl::pi::Audio::audioCallbackPA(const void*, void*, long unsigned int, const PaStreamCallbackTimeInfo*, PaStreamCallbackFlags, void*)':
> /home/pi/pink-0/src/Audio.cpp:112:51: error: request for member 'sampleTimeToHostTime' in 'platform.sl::pi::Audio::m_hostTimeFilter', which **is of non-class type 'int'**
>    const auto hostTime = platform.m_hostTimeFilter.sampleTimeToHostTime(platform.m_sampleTime);
>                                                    ^~~~~~~~~~~~~~~~~~~~
> CMakeFiles/pink.dir/build.make:62: recipe for target 'CMakeFiles/pink.dir/src/Audio.cpp.o' failed
> make[2]: *** [CMakeFiles/pink.dir/src/Audio.cpp.o] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pink.dir/all' failed
> make[1]: *** [CMakeFiles/pink.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by shaduzlabs** [comment]
My bad, I updated the Ableton Link submodule and forgot to commit the necessary patches to adapt to the changes in the Link API. Could you please retry?

**Comment by endlesssummer2000** [comment]
thanks!
