### ISSUE TITLE
How do I confirm that it's running with no-ui?

### ISSUE THREAD

**Issue by zhagan** [shaduzlabs/pink-0#2]
I was able to run the install script on a rpi 3,

`sudo bash ./install.sh no-ui`

 I get all the way to:

[ pink ] Installation completed, please reboot now.

I reboot and I can login to pink-ap, but I don't think that link is actually running... forgive my noobness with linux but how can I confirm it's actually running? I looked through the processes but can't seem to pick it out. I've also tried just starting it manually, but I still don't see it as a peer in any other Link app. Any insight would be appreciated. Thanks!``

**Comment by shaduzlabs** [comment]
I just checked on a rpi 3, the daemon works but it isn't auto-started. The installation script is now fixed, you can pull the changes and then, from the build folder, run:
```
make
sudo make install
```
In general, you can check the service status by typing `sudo service pink status`.
You can start it manually with `sudo service pink start` and stop it with `sudo service pink stop`

**Comment by zhagan** [comment]
Just tested it and it works! Thanks so much!

**Comment by Skeyelab** [comment]
Hey, so I'm in a similar state.  I installed this on a Raspi Zero Wireless and the service is running according to `sudo service pink status`, but I'm not seeing it show up as a peer.

**Comment by shaduzlabs** [comment]
@Skeyelab still having issues? Were you able to solve the problem?
